#! /bin/sh
#
#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements.  See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# BTest helper for getting values for Zeek-related environment variables.

base=$(dirname "$0")
zeek=$(grep ZEEK_DIST "${base}/../../build/CMakeCache.txt" | cut -d = -f 2)

if [ "$1" = "zeekbase" ]; then
    echo "${zeek}"
elif [ "$1" = "zeekpath" ]; then
    "${zeek}/build/zeek-path-dev"
elif [ "$1" = "zeek_plugin_path" ]; then
    ( cd "${base}/../.." && pwd )
elif [ "$1" = "zeek_seed_file" ]; then
    echo "${zeek}/testing/btest/random.seed"
elif [ "$1" = "path" ]; then
    echo "${zeek}/build/src:${zeek}/aux/btest:${base}/:${zeek}/aux/zeek-cut:$PATH"
else
    echo "usage: $(basename "$0") <var>" >&2
    exit 1
fi
